name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
          
      - name: Build
        run: make build
        
      - name: Run tests
        run: |
          swift package generate-xcodeproj
          xcodebuild test -scheme PwgenSwift-Package -derivedDataPath .build/derived -destination platform=macOS -enableCodeCoverage YES | xcpretty
        
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
