name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
          
      - name: Build
        run: make build
        
      - name: Run tests
        run: make test
        
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./.build/debug/codecov/PwgenSwift.json
          flags: unittest
          fail_ci_if_error: true
          verbose: true
